name: Deploy

on:
  push:
    branches: [ remitocat/main ]
  pull_request:
    branches: [ remitocat/main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      USERNAME: ${{ secrets.SSH_USERNAME }}
      HOST: ${{ secrets.SSH_HOST }}
      PORT: ${{ secrets.SSH_PORT }}
    steps:
      - run: |
          mkdir -p ~/.ssh/
          echo "${PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -oStrictHostKeyChecking=no ${USERNAME}@${HOST} -i ~/.ssh/id_rsa -p ${PORT}
          cd mastodon && git fetch origin && git pull origin chillout-chat/main
          docker-compose build
          docker-compose run --rm web rails db:migrate
          docker-compose run --rm web rails assets:precompile
          docker-compose up -d --remove-orphans
          docker system prune -f
