name: Deploy

on:
  push:
    branches: [ chillout-chat/main ]
  pull_request:
    branches: [ chillout-chat/main ]

env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  USERNAME: ${{ secrets.SSH_USERNAME }}
  HOST: ${{ secrets.SSH_HOST }}
  PORT: ${{ secrets.SSH_PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -oStrictHostKeyChecking=no ${USERNAME}@${HOST} -i ./private_key -p ${PORT}
          cd mastodon && git fetch origin && git pull origin chillout-chat/main
          docker-compose build
          docker-compose run --rm web rails db:migrate
          docker-compose run --rm web rails assets:precompile
          docker-compose up -d --remove-orphans
          docker system prune -f
